#!/bin/bash
set -o xtrace

out=`ps aux | grep python |  grep "$@" | grep -v "$@.sh" | grep -v "nkill" | grep -v instan | grep -v ssh | grep -v grep | grep -v rabbitmq | grep python | wc -l`
if [[ $out -gt 0 ]]; then
     ps aux | grep python | grep "$@" | grep -v "$@.sh" | grep -v "nkill" | grep -v instan | grep -v ssh | grep -v grep | grep -v rabbitmq | grep python | awk '{print $2}' | xargs -i kill -9 {}
fi

set +o xtrace
